# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'BJJ_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  pod 'SnapKit'
  pod 'Then'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Cosmos'

  use_frameworks!

  # Pods for BJJ_iOS

  target 'BJJ_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BJJ_iOSUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
